Repository mad201802/firstpass, pull requests merged in 2023-02, with the labels that each got.

#127 Added clean readme and license
  LICENSE
  README.md
  frontend/package.json
  package.json
Labels: documentation

#130 #129 add jsdoc for global components
  frontend/app/src/components/AnimatedPatternBG/AnimatedPatternBG.js
  frontend/app/src/components/Button/Button.js
  frontend/app/src/components/CheckBoxProp/CheckBoxProp.js
  frontend/app/src/components/ColorProp/ColorProp.js
  frontend/app/src/components/DropdownMenu/DropdownMenu.js
  frontend/app/src/components/EditableProp/EditableProp.js
  frontend/app/src/components/ErrorMessage/ErrorMessage.js
  frontend/app/src/components/FormInput/FormInput.js
  frontend/app/src/components/PasswordStrength/PasswordStrength.js
  frontend/app/src/components/Popup/Popup.js
  frontend/app/src/components/TitleBar/TitleBar.js
  frontend/app/src/components/Tooltip/Tooltip.js
  frontend/app/src/components/UrlLogo/UrlLogo.js
Labels: documentation, frontend

#138 updated CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#139 Feature/readme badges
  README.md
Labels: documentation

#140 New readme and changelog
  CHANGELOG.md
  README.md
  frontend/app/src/components/AnimatedPatternBG/AnimatedPatternBG.js
  frontend/app/src/components/Button/Button.js
  frontend/app/src/components/CheckBoxProp/CheckBoxProp.js
  frontend/app/src/components/ColorProp/ColorProp.js
  frontend/app/src/components/DropdownMenu/DropdownMenu.js
  frontend/app/src/components/EditableProp/EditableProp.js
  frontend/app/src/components/ErrorMessage/ErrorMessage.js
  frontend/app/src/components/FormInput/FormInput.js
  frontend/app/src/components/PasswordStrength/PasswordStrength.js
  frontend/app/src/components/Popup/Popup.js
  frontend/app/src/components/TitleBar/TitleBar.js
  frontend/app/src/components/Tooltip/Tooltip.js
  frontend/app/src/components/UrlLogo/UrlLogo.js
Labels: documentation

#142 Backend code cleanup and javadoc
  backend/src/main/java/io/firstpass/database/drivers/SQLiteDriver.java
  backend/src/main/java/io/firstpass/encryption/symmetric/ISymmetricEncryptionAlgorithm.java
  backend/src/main/java/io/firstpass/encryption/symmetric/algos/AES256.java
  backend/src/main/java/io/firstpass/ipc/exceptions/IPCException.java
  backend/src/main/java/io/firstpass/ipc/interfaces/IOnMessageRecieve.java
  backend/src/main/java/io/firstpass/ipc/parser/IMessageParser.java
  backend/src/main/java/io/firstpass/logic/StrengthAnalyzer.java
Labels: backend

#147 fix standalone distribution fatal error issue
  README.md
  frontend/package.json
  frontend/util/backend.js
  package.json
Labels: bug

#148 add mac code sign info to readme
  README.md
Labels: documentation

#149 add mac code sign info to readme
  README.md
Labels: documentation
